# Generated by Django 2.2.5 on 2019-09-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_itens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ataque',
            new_name='Item',
        ),
    ]
