# Generated by Django 2.2.5 on 2019-09-22 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_itens', '0002_auto_20190921_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAtaque',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_itens.Item')),
            ],
            bases=('app_itens.item', models.Model),
        ),
        migrations.RemoveField(
            model_name='item',
            name='nome',
        ),
    ]
