# Generated by Django 2.2.5 on 2019-09-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_itens', '0004_categoria_idefesa_imagico'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cat',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='iataque',
            name='dano',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='idefesa',
            name='defesa',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='imagico',
            name='poderMagico',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='nome',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='valor',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
